name: Update Language Chart

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate SVG
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # your custom token if needed in script.js
        run: node script.js

      - name: Commit and push SVG
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # Use your PAT here
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/${{ github.repository }}.git
          git add language-stats.svg
          git diff --cached --quiet || git commit -m "Update language stats chart"
          git push
