name: Update Language Chart

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node generate.js  # or the filename of your script

      - name: Commit and push SVG
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add language-stats.svg
          git commit -m "Update language stats chart" || echo "No changes"
          git push

