name: Update Language Chart

on:
  push:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}  # pass the secret here
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate SVG
        run: node script.js   # your script filename

      - name: Commit and push SVG
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add language-stats.svg
          git diff --cached --quiet || git commit -m "Update language stats chart"
          git push
